# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmpo < Formula
  desc "Minimal CLI time tracker for developers"
  homepage "https://github.com/DylanDevelops/tmpo"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.6.0/tmpo_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "875cf974ae982e2f0d923218f03362bfa0400f6b937d037289b2c1dbf0dd1223"

      define_method(:install) do
        bin.install "tmpo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.6.0/tmpo_0.6.0_Darwin_arm64.tar.gz"
      sha256 "f0c8d5a0bd3a5571d027520806121560eb882870a29546127b6190c336055cce"

      define_method(:install) do
        bin.install "tmpo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.6.0/tmpo_0.6.0_Linux_x86_64.tar.gz"
      sha256 "b8cd3e990f50b4e92f9684f3379a21ded131fd4079da47ca04fedb5c11620875"
      define_method(:install) do
        bin.install "tmpo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DylanDevelops/tmpo/releases/download/v0.6.0/tmpo_0.6.0_Linux_arm64.tar.gz"
      sha256 "c0fa348bacdf6da59dfb7c0651ec631b63a785c6ddc49104e9690875bd4e83f9"
      define_method(:install) do
        bin.install "tmpo"
      end
    end
  end

  test do
    system "#{bin}/tmpo", "--version"
  end
end
