# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmpo" do
  name "tmpo"
  desc "Minimal CLI time tracker for developers"
  homepage "https://github.com/DylanDevelops/tmpo"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmpo"
  bash_completion "completions/tmpo.bash"
  zsh_completion "completions/tmpo.zsh"
  fish_completion "completions/tmpo.fish"

  on_macos do
    on_intel do
      url "https://github.com/DylanDevelops/tmpo/releases/download/v#{version}/tmpo_#{version}_Darwin_x86_64.tar.gz"
      sha256 "97904c82680b128e68b87c0b376fa9f8147b1fd3987a3732f047f69b4a24b733"
    end
    on_arm do
      url "https://github.com/DylanDevelops/tmpo/releases/download/v#{version}/tmpo_#{version}_Darwin_arm64.tar.gz"
      sha256 "5dacaf39ebc521b2e5b518e50b9827e029c4f9b8b78ce6797233256ece7e0217"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DylanDevelops/tmpo/releases/download/v#{version}/tmpo_#{version}_Linux_x86_64.tar.gz"
      sha256 "fa954196d10fa9a7f2cda8493ec35b6677700f63020d27f64b92b5a59e6c7f5f"
    end
    on_arm do
      url "https://github.com/DylanDevelops/tmpo/releases/download/v#{version}/tmpo_#{version}_Linux_arm64.tar.gz"
      sha256 "4f2a1d687be81551b67e5cc126dba22e83434c0bff28b225253fb73e659f3a91"
    end
  end

  # No zap stanza required
end
